version: '3.7'

networks:
  default:
    external:
      name: db_net

services:
  wordpress:
    env_file:
      - ./.env
    container_name: WP__${PROJECT_NAME}
    # development image
    image: ghcr.io/hansanghyeon/wordpress-php8.0-docker-xdebug3.0:1.0.0
    restart: always
    ports:
      - ${PROJECT_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./.wordpress:/var/www/html
      - ./Theme:/var/www/html/wp-content/themes/sage
      - ./DEV:/var/www/html/wp-content/themes/dev
      - ./backup:/var/www/html/wp-content/ai1wm-backups
    external_links:
      - DB__wordpress:mariadb
